### ISSUE TITLE
验证器验证结果有误

### ISSUE THREAD

**Issue by codeingist** [inhere/php-validate#10]
![TIM截图20190621202657](https://user-images.githubusercontent.com/30253365/59922288-0d75ae00-9463-11e9-90fc-2db40a68b2e5.png)
验证器结果有误，验证一个值是否为整形时，传入一个0提示: must be an integer!
不符合预期结果

**Comment by codeingist** [comment]
![TIM截图20190621202814](https://user-images.githubusercontent.com/30253365/59922387-44e45a80-9463-11e9-8e79-43863ea2c18c.png)

**Comment by codeingist** [comment]
![TIM截图20190621203109](https://user-images.githubusercontent.com/30253365/59922506-8412ab80-9463-11e9-81db-1291787a6133.png)

**Comment by inhere** [comment]
验证是检查到了的，但是提示消息错了是吧？是最新的版本吗？

**Comment by codeingist** [comment]
> 验证是检查到了的，但是提示消息错了是吧？是最新的版本吗？

最新版，验证是检测到了值不符合限定规则，就是返回的错误信息有误。而且貌似仅在使用数组的这种形式才触发这个bug，如果是使用|分隔符来注册验证规则则不会触发
