### ISSUE TITLE
数组验证异常结果错误

### ISSUE THREAD

**Issue by Hhhha** [inhere/php-validate#15]
原始数据请求数据：
![图片](https://user-images.githubusercontent.com/29363368/63483330-a14d1000-c4ce-11e9-9456-edbb501e729f.png)
验证规则：
![图片](https://user-images.githubusercontent.com/29363368/63483353-b164ef80-c4ce-11e9-8605-c4808608f069.png)
消息提示：
![图片](https://user-images.githubusercontent.com/29363368/63483367-b9bd2a80-c4ce-11e9-9381-4f86adb875f7.png)
版本：
"inhere/php-validate": "^2.7"

**Comment by inhere** [comment]
你这数据错了吧！如果数据是这样：

```php
[
	'categories' => [
		'name' => 'tom',
		'parent_id' => 23,
	]
]
```

你上面的规则才是正确的。你发的数据还多了一级，`categories.name` 是不存在的啊。

你改下规则为 `['categories.*.name', 'each', 'required']` 试试.
参考测试里：

https://github.com/inhere/php-validate/blob/2426184320d07546951734dcfbd519472351656e/test/RuleValidationTest.php#L541-L562

**Comment by Hhhha** [comment]
![图片](https://user-images.githubusercontent.com/29363368/63484053-f4c05d80-c4d0-11e9-8f86-8c1c98516b95.png)
如果我是这样的数据请问怎么验证呢

**Comment by inhere** [comment]
跟前面的数据不是一样的吗？ 只是少了key。 可以传入时手动加个key：

```php
Validation::check(['categories' => $yourData] ....)
```

就跟之前的没撒区别了。

**Comment by Hhhha** [comment]
我还有个问题，我看check方法的注释是有异常的 ，现在验证的时候不会自动拋异常，请问是需要配置什么东西吗

**Comment by inhere** [comment]
正常验证基本上不会抛异常。 只有你写错 验证器名字 之类的会报异常。

**Comment by Hhhha** [comment]
现在是验证不同过的时候也不会拋异常，需要我手动去isFail  我现在想自动抛出异常

**Comment by inhere** [comment]
你可以继承我里面的 Validation 在validate 后，用 isFail 检查下，失败了你拋个异常。
然后你使用你自己的类，就行了。

**Comment by Hhhha** [comment]
数据结构：
![图片](https://user-images.githubusercontent.com/29363368/63503754-a3c95d00-c502-11e9-82d7-482e34c9517d.png)
验证规则：
![图片](https://user-images.githubusercontent.com/29363368/63503767-a926a780-c502-11e9-85e3-238fe054b3c3.png)
结果：
![图片](https://user-images.githubusercontent.com/29363368/63503796-bd6aa480-c502-11e9-9d08-586a5a848f3c.png)
我这个规则有什么问题吗

**Comment by inhere** [comment]
现在暂时不支持这样用，`*` 只能靠近最后一个字段。 😄  解析拿数据太麻烦了。

**Comment by Hhhha** [comment]
希望可以支持一下，毕竟传递一个复杂的数组还是会用到这个功能的
