### ISSUE TITLE
requiredIf 规则实现有错误

### ISSUE THREAD

**Issue by nemoTyrant** [inhere/php-validate#2]
`requiredIf` 的规则应该是: 另一个字段等于某值时，本字段必须; 如果不等于，则不应该检查本字段。

但是在我使用的 `v2.4.11` 版本中，无论另一个字段是否等于某值，本字段都必须。
原因是 `UserAndContextValidatorsTrait.php 178行` 判断另一字段不在匹配值中时直接返回了false。

假设改为`return true`让程序暂时正常进行

另外一个问题是，如果本字段不存在，在getSafeData()的时候会返回一个值为`null`的字段，我认为不应该返回这个字段。

**Comment by inhere** [comment]
我下来看看， 你有兴趣的话可以发个 PR 修复下

我其实很少用 `required*` 的规则。 

我用 `required` + `when` 来做类似的验证，用习惯了

**Comment by inhere** [comment]
已经修复，可以更新试下。

**Comment by nemoTyrant** [comment]
好的。你这个项目功能很强大，不知道为啥星这么少，还好我发现了这块宝。我会持续关注的，看看还能不能发现别的问题。哈哈！
