### ISSUE TITLE
类似 product.*.properties 这种规则验证的疑问

### ISSUE THREAD

**Issue by Niexiawei** [inhere/php-validate#20]
![image](https://user-images.githubusercontent.com/29922984/65234418-1c720800-db07-11e9-9a01-9f6d562db5f3.png)

当设置 max 验证无法通过

![image](https://user-images.githubusercontent.com/29922984/65292594-9b5c5480-db8a-11e9-9acd-6428a4cc51b7.png)

去除 max 就正常了

**Comment by inhere** [comment]
更新到最新版本可以了。 `v2.8.0`
