### ISSUE TITLE
验证前的操作问题

### ISSUE THREAD

**Issue by dongasai** [inhere/php-validate#28]
我发现了你有`onBeforeValidate`这个功能,这证明你也发现了验证前可能需要一些神奇的操作,那么我就纳闷了,既然可以定义`validation`类,那么为什么不把这些个操作放在`验证`类内部执行呢?

ps:一顿分离猛如虎,一个耦合乱如麻呀!

**Comment by dongasai** [comment]
你还不写文档,我今个才发现这个功能,晚上写个文档,提交个pr

**Comment by inhere** [comment]
哈哈 又遇到特殊情况的想跳过验证，或者想在验证前做一些固定调整，就可以使用这个。

> 有些细节性的地方就没写出来了，也有可能是写的时候没想到

**Comment by dongasai** [comment]
对,确认验证必要条件,如果不成立,那么验证旧没必要进行下去了

**Comment by dongasai** [comment]
#29

**Comment by inhere** [comment]
@dongasai  thanks.
