### ISSUE TITLE
readme中关于自定义规则的介绍有误

### ISSUE THREAD

**Issue by nemoTyrant** [inhere/php-validate#3]
在方式1中提到自定义规则使用：

> ['title', 'customValidator', 'msg' => '{attr} error msg!' ], // 指定当前规则的消息

并且自定义了一个方法：
```
// 添加一个验证器。必须返回一个布尔值标明验证失败或成功
    protected function customValidator($title)
    {
        // some logic ...

        return true; // Or false;
    }
```

实际使用过程中，应用自定义规则名称不能使用"customValidator"，而应该是"custom"。因为底层在执行验证时对方法名做了拼接。

**Comment by inhere** [comment]
bug fixed: https://github.com/inhere/php-validate/commit/48594b8cadf8a06c446b0fe683895c531837d5f7
