### ISSUE TITLE
多维数组不走required验证string时的问题

### ISSUE THREAD

**Issue by cpj555** [inhere/php-validate#33]
![image](https://user-images.githubusercontent.com/19289096/98754718-3d2fa800-2402-11eb-90e4-07534ff7df10.png)
![image](https://user-images.githubusercontent.com/19289096/98754675-28ebab00-2402-11eb-92ee-a8df6d6a70ce.png)

![image](https://user-images.githubusercontent.com/19289096/98755154-f5f5e700-2402-11eb-859f-f36e61eac5de.png)
![image](https://user-images.githubusercontent.com/19289096/98755185-0ad27a80-2403-11eb-8e52-075c828c6b3c.png)

当没有验证required的时候,多维数组过empty验证没有通过continue掉,接着带着object(ArrayValueNotExists)  往下调String验证就return false了

**Comment by boobusy** [comment]
带 .*  的规则 需要自己添加 isEmpty 验证是否为空, 此时注意: isEmpty 函数参数为数组.
