### ISSUE TITLE
rules里自定义闭包来做验证规则时候的参数问题

### ISSUE THREAD

**Issue by skywowleo** [inhere/php-validate#38]
```php
['UserId', function($field, $data) {
            var_dump($data, $value);
}],
```
这个闭包看源码第一个参数是UserId的值,第二个值应该是整个rules才对,为啥打印出来的是我传进去的整个待校验data数组信息呢?

**Comment by inhere** [comment]
第一个参数是字段值，紧跟着时验证器需要的参数(部分验证器有比如size需要传入范围大小)，最后一个参数总是 `$data`

**Comment by skywowleo** [comment]
```
$validator = array_shift($rule);   //先把rule里的验证规则弹出去
$args = $rule; 
$args[] = $this->data; // 把要校验的整个数组放到args里
$passed = $validator($value, ...$args);  // 所以最后参数就变成了 目标字段的值, 剩余rule信息,整个校验参数的$data
```
只不过在我写的例子里, rule里 只有一个 callable, 所以 被array_shift后 其实就是一个空数组了, 所以我打印$data 的时候 其实就是 整个 待校验的 $data

**Comment by inhere** [comment]
`$rule` 在前面已经经过一些处理了。到 `array_shift` 这里就只剩下 验证器和验证器参数了(没有参数的，就只有验证器了)

你是需要啥信息吗？

**Comment by skywowleo** [comment]
没有问题了,我一开始不理解 为什么闭包的第二个参数是整个`$data`,后来根据你的回复我看了一遍代码现在明白了所以我上面第二个回复其实是给自己的问题写个答复 😁

**Comment by inhere** [comment]
好的，有发现问题欢迎提PR改进 :)
