### ISSUE TITLE
reuqire了toolkit/stdlib引起的坑

### ISSUE THREAD

**Issue by cpj555** [inhere/php-validate#52]
一般env这个函数都是框架会自己写一个的, composer自动加载有时候会把这个env先加载导致env函数优先使用toolkit/stdlib中的,太坑了。。。

**Comment by cpj555** [comment]
![image](https://user-images.githubusercontent.com/19289096/144429524-db3a3230-bbdf-4d5b-bbfd-9ec73f9c4f62.png)

**Comment by inhere** [comment]
https://github.com/php-toolkit/stdlib/releases/tag/v1.2.0 已经调整 `env()` 重命名为 `env_val()`

see: 

https://github.com/php-toolkit/stdlib/blob/a33c3ccc63f388c81a75d0fec3893c9d0212286b/src/func.php#L116-L126
