### ISSUE TITLE
为什么getErrors只抛出一条异常信息？

### ISSUE THREAD

**Issue by juvenrui** [inhere/php-validate#54]
$v = \Inhere\Validate\Validation::check([
    'title' => 'loggerSaveTime',
    'age' => 2,
], [
    ['title', 'min', 30, 'msg' => '标题字数无效!'],
    ['age', 'int', 'min'=>4, 'max'=>16, 'msg' => '{attr} error!'],
]);
if ($v->isFail()) {
    var_dump($v->getErrors());
    //var_dump($v->firstError(!false));
}

getErrors只抛出一条异常信息:

<img width="445" alt="截屏2022-07-17 12 07 06" src="https://user-images.githubusercontent.com/4530373/179383541-9e3712b0-33ab-4a7e-850c-b1fb910327da.png">

**Comment by inhere** [comment]
因为默认是 `stopOnError=true` 遇到第一个错误就会停止继续验证，这样性能更好点。

你可以设置为 false 就会把全部规则都进行验证，这样可以得到所有的验证错误

**Comment by juvenrui** [comment]
> 因为默认是 `stopOnError=true` 遇到第一个错误就会停止继续验证，这样性能更好点。
> 
> 你可以设置为 false 就会把全部规则都进行验证，这样可以得到所有的验证错误

谢谢回复。

已在ErrorMessageTrait.php文件中找到该参数。在readme中未找到如何全局设置？

**Comment by juvenrui** [comment]
找到解决方案：
$v = Validation::make($_POST, [
    // [...],
    // some rules ...
])
->setStopOnError(false)
->validate();

PS: 很棒的验证器。👍
