### ISSUE TITLE
safe 字段有问题

### ISSUE THREAD

**Issue by MkMarko** [inhere/php-validate#9]
例如save字段填写更新时间和修改时间，那当外部传入created_at和updated_at时，则会修改你本身填入save的字段里，从而改变你的创建时间与修改时间，这是一个很大的bug

**Comment by inhere** [comment]
`safe` 是内部使用的，作为开发者你是明确知道这个字段是安全的无需验证，可以加上 `safe` 只做收集不验证。

如果这个字段是外部传入的，则不应该加上 safe 标记。
